version: "3.6"

services:
  catalog_db:
    image: mongo
    container_name: catalog_db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  catalog-api:
    image: ${DOCKER_REPOSITORY-}catalog-api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog_db:27017"
    depends_on:
      - catalog_db
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
    ports:
      - "8001:80"
