version: "3.6"

services:
  catalog_db:
    image: mongo
    container_name: catalog_db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  basket_db:
    image: redis
    container_name: basket_db
    restart: always
    ports:
      - "6379:6379"
  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog_api:
    container_name: catalog_api
    image: ${DOCKER_REPOSITORY-}catalog_api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog_db:27017"
    depends_on:
      - catalog_db
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
    ports:
      - "8001:80"

  basket_api:
    container_name: basket_api
    image: ${DOCKER_REGISTRY-}basket_api
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basket_db:6379"
      - "EventBus:HostName=rabbit_mq"
      - "EventBus:UserName=guest"
      - "EventBus:Password=guest"
    depends_on:
      - basket_db
      - rabbit_mq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"
